### ISSUE TITLE
can't use plain array in `in_parallel`

### ISSUE THREAD

**Issue by phil9909** [cappyzawa/concourse-pipeline-jsonschema#1]
When I validate a pipeline with `in_parallel` like this one:
```yaml
jobs:
- name: job
  plan:
  - in_parallel:
    - get: a
    - get: b
```
Which should be valid according [concourse docs](https://concourse-ci.org/jobs.html#schema.step.in-parallel-step.in_parallel): 
> Steps are either configured as a array or within a in_parallel_config schema.

I see `.jobs[0].plan[0].in_parallel expected object got: array`.

---

I took a look at the schema:
```json
"InParallelConfig": {
	"properties": {
		"steps": {
			"items": {
				"$ref": "#/definitions/PlanConfig"
			},
			"type": "array"
		},
		"limit": {
			"type": "integer"
		},
		"fail_fast": {
			"type": "boolean"
		}
	},
	"additionalProperties": false,
	"type": "object"
},
```
and
```json
"in_parallel": {
	"$schema": "http://json-schema.org/draft-04/schema#",
	"$ref": "#/definitions/InParallelConfig"
},
```
It is indeed wrong here.

**Comment by cappyzawa** [comment]
This tool generates the schema based on this struct (https://github.com/concourse/concourse/blob/master/atc/config.go#L21).

The `InParallelConfig` is generated based on https://github.com/concourse/concourse/blob/master/atc/config.go#L354. 

For these reasons, this schema allows object only in spite of the `in_parallel` step allows both object and array.

Thanks for submitting this issue.
