### ISSUE TITLE
Step schema generated with different properties

### ISSUE THREAD

**Issue by gmsantos** [cappyzawa/concourse-pipeline-jsonschema#3]
I noticed after configuring the schema with some pipelines a few warnings for properties inside the plan and other schemas. They are related to the Step definition, which should have the step schema from here: https://concourse-ci.org/jobs.html#schema.step

However, the following Step definition is generated:

```
        "Step": {
            "required": [
                "Config",
                "UnknownFields"
            ],
            "properties": {
                "Config": {
                    "additionalProperties": true
                },
                "UnknownFields": {
                    "patternProperties": {
                        ".*": {
                            "items": {
                                "type": "integer"
                            },
                            "type": "array"
                        }
                    },
                    "type": "object"
                }
            },
            "additionalProperties": false,
            "type": "object"
        },
```

I think it's because the Step struct is a special struct in application code (see https://github.com/concourse/concourse/blob/master/atc/steps.go#L12-L17).

Any idea on how to fix that? Maybe using the actual struct for each type (https://github.com/concourse/concourse/blob/master/atc/steps.go#L290-L371) instead the main one.

**Comment by simpoir** [comment]
You might be able to work around the lack of reflection for dynamic interfaces by listing and merging the known types definitions. 

Here's a gist of what I have in mind:

https://gist.github.com/4662752c4af75b3220d94b657683d090

The end-result seems to me to be closer to the full schema, but I'm not fluent enough in concourse pipelines to really say.

**Comment by cappyzawa** [comment]
@simpoir 
Your suggestion is implemented in https://github.com/cappyzawa/concourse-pipeline-jsonschema/commit/b04450d1f4d60a82fabd8d2190c9ca883670272b .

Thanks for your help 🥰 

@gmsantos Thanks for reporting this!
